name: Main

on:
  push:
    tags:
      - 1.**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./build.sh -p --net --no-gui

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/packages/renode-*.linux-dotnet.tar.gz
